version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      # build and push Docker image
      - run: docker build -t $DOCKER_REPO:latest .
      - run: |
          echo $DOCKER_PASSWD | docker login registry.cn-hangzhou.aliyuncs.com -u $DOCKER_USER --password-stdin 
          docker push $DOCKER_REPO:latest