version: 2.1
jobs:
  build:
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      # build and push Docker image
      - run: docker build -t $DOCKER_REPO:latest .
      - run: |
          echo $DOCKER_PASSWD | docker login registry.cn-hangzhou.aliyuncs.com -u $DOCKER_USER --password-stdin 
          docker push $DOCKER_REPO:latest